runtime: python311
entrypoint: gunicorn -b :$PORT maintenance_project.wsgi
# service: default
service: clubs-service

instance_class: F1

env_variables:
  DJANGO_SETTINGS_MODULE: "maintenance_project.settings"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1

handlers:
- url: /static
  static_dir: static
- url: /images/Uploads
  static_dir: static/images/Uploads
- url: /.*
  script: auto
